export const PRODUCTS = [
  {
    id: 1,
    slug: 'pro-wireless-headphones',
    name: 'Pro Wireless Headphones',
    price: 149,
    originalPrice: 199,
    category: 'Audio',
    tagline: 'Studio-grade sound, all-day comfort',
    description: 'Experience music the way it was meant to be heard. The Pro Wireless Headphones deliver 40mm drivers tuned for audiophile-grade clarity across every genre. Adaptive noise cancellation and a 40-hour battery keep you in the zone from morning standup to late-night deep work.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1487215078519-e21cc028cb29?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.8,
    reviewCount: 312,
    inStock: true,
    lowStock: false,
    isBestseller: true,
    isNew: false,
    features: ['40-hour battery life', 'Active noise cancellation', 'Foldable premium design', 'USB-C fast charging', 'Hi-Res Audio certified', 'Multipoint Bluetooth 5.3'],
    translations: {
      hu: {
        name: 'Prémium Wireless Fejhallgató',
        tagline: 'Stúdióminőségű hang, egész napos kényelem',
        description: 'Tapaszd meg a zenét úgy, ahogy szánták. A Prémium Wireless Fejhallgató 40mm-es membránjait audiofil hangzásra hangolták minden zenei stílushoz. Az adaptív zajszűrés és a 40 órás akkumulátor egész nap – a reggeli meetingtől a késő éjszakai mélymunkáig – fókuszban tart.',
        features: ['40 órás akkumulátor', 'Aktív zajszűrés', 'Összecsukható prémium kialakítás', 'USB-C gyorstöltés', 'Hi-Res Audio tanúsítvánnyal', 'Többpontos Bluetooth 5.3'],
      },
      tr: {
        name: 'Pro Kablosuz Kulaklık',
        tagline: 'Stüdyo kalitesinde ses, tüm gün konfor',
        description: 'Müziği duyulması gerektiği gibi deneyimleyin. Pro Kablosuz Kulaklık, her müzik türünde audiofil netliği için ayarlanmış 40mm sürücülerle geliyor. Adaptif gürültü engelleme ve 40 saatlik pil, sabahki toplantıdan gece geç saatlere kadar sizi odakta tutar.',
        features: ['40 saatlik pil ömrü', 'Aktif gürültü engelleme', 'Katlanabilir premium tasarım', 'USB-C hızlı şarj', 'Hi-Res Audio sertifikalı', 'Çok noktalı Bluetooth 5.3'],
      },
    },
  },
  {
    id: 2,
    slug: 'mechanical-keyboard-tkl',
    name: 'Mechanical Keyboard TKL',
    price: 199,
    originalPrice: null,
    category: 'Workspace',
    tagline: 'Tactile precision, tenkeyless form',
    description: 'Built for those who live in the terminal. The TKL uses custom linear switches rated for 100 million keystrokes and a hot-swap PCB so you can re-tune your feel anytime. PBT double-shot keycaps resist fade years into daily use.',
    image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.7,
    reviewCount: 188,
    inStock: true,
    lowStock: false,
    isBestseller: false,
    isNew: true,
    features: ['Hot-swap PCB', 'PBT double-shot keycaps', 'USB-C detachable cable', 'Per-key RGB backlight', 'CNC aluminium case', 'Custom linear switches'],
    translations: {
      hu: {
        name: 'Mechanikus Billentyűzet TKL',
        tagline: 'Taktilis precizitás, tenkeyless forma',
        description: 'Azoknak, akik a terminálban élnek. A TKL egyedi lineáris kapcsolókat használ, 100 millió billentyűleütésre minősítve, cserélhető PCB-vel, hogy bármikor finomhangolhasd az érzetet. A PBT double-shot billentyűsapkák éveken át ellenállnak a kopásnak.',
        features: ['Hot-swap PCB', 'PBT double-shot billentyűsapkák', 'USB-C levehető kábel', 'Billentyűnkénti RGB háttérvilágítás', 'CNC alumínium ház', 'Egyedi lineáris kapcsolók'],
      },
      tr: {
        name: 'Mekanik Klavye TKL',
        tagline: 'Taktil hassasiyet, tenkeyless form',
        description: 'Terminalde yaşayanlar için tasarlandı. TKL, 100 milyon tuş basımına ömürlü özel lineer anahtarlar ve istediğiniz zaman hissi yeniden ayarlayabileceğiniz hot-swap PCB kullanır. PBT double-shot tuş başlıkları yıllarca günlük kullanımda solmaya direnir.',
        features: ['Hot-swap PCB', 'PBT double-shot tuş başlıkları', 'USB-C çıkarılabilir kablo', 'Tuş başına RGB aydınlatma', 'CNC alüminyum kasa', 'Özel lineer anahtarlar'],
      },
    },
  },
  {
    id: 3,
    slug: 'usb-c-hub-12-in-1',
    name: 'USB-C Hub 12-in-1',
    price: 89,
    originalPrice: null,
    category: 'Workspace',
    tagline: 'Every port you need, one cable',
    description: 'Reclaim every port on your laptop without sacrificing desk clarity. Twelve connections—HDMI 4K, USB-A 3.2, Ethernet, SD cards, and 100W PD passthrough—pack into an aluminium body smaller than your palm.',
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1625895197185-efcec01cffe0?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1563206767-5b18f218e8de?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.6,
    reviewCount: 245,
    inStock: true,
    lowStock: false,
    isBestseller: false,
    isNew: false,
    features: ['4K HDMI output', '100W Power Delivery', 'USB-A 3.2 Gen 2 (×3)', 'SD & microSD slots', 'Gigabit Ethernet', 'Aluminium heatsink body'],
    translations: {
      hu: {
        name: 'USB-C Hub 12-az-1-ben',
        tagline: 'Minden port, egyetlen kábel',
        description: 'Szeresd vissza laptopod minden portját az asztali rend megőrzésével. Tizenkét csatlakozás – HDMI 4K, USB-A 3.2, Ethernet, SD kártyák és 100W PD átvitel – fér el egy tenyérnél kisebb alumínium házban.',
        features: ['4K HDMI kimenet', '100W Power Delivery', 'USB-A 3.2 Gen 2 (×3)', 'SD és microSD foglalat', 'Gigabit Ethernet', 'Alumínium hűtőbordás ház'],
      },
      tr: {
        name: 'USB-C Hub 12si 1 Arada',
        tagline: 'İhtiyacınız olan her port, tek kablo',
        description: 'Masa düzeninden ödün vermeden laptopunuzdaki tüm portları geri kazanın. HDMI 4K, USB-A 3.2, Ethernet, SD kartlar ve 100W PD geçiş dahil on iki bağlantı, avucunuzdan küçük alüminyum bir gövdeye sığıyor.',
        features: ['4K HDMI çıkışı', '100W Power Delivery', 'USB-A 3.2 Gen 2 (×3)', 'SD ve microSD yuvaları', 'Gigabit Ethernet', 'Alüminyum soğutma gövdesi'],
      },
    },
  },
  {
    id: 4,
    slug: 'aluminum-laptop-stand',
    name: 'Aluminum Laptop Stand',
    price: 69,
    originalPrice: null,
    category: 'Workspace',
    tagline: 'Elevate your screen, elevate your posture',
    description: 'Six adjustable height positions and a solid aluminium build make this the last stand your desk will ever need. Non-slip silicone pads protect your laptop and keep the stand planted under the most intense typing sessions.',
    image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1593642634315-48f5414c3ad9?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.9,
    reviewCount: 427,
    inStock: true,
    lowStock: false,
    isBestseller: true,
    isNew: false,
    features: ['6-angle height adjustment', 'Solid aluminium alloy', 'Non-slip silicone pads', 'Foldable & portable', 'Compatible with 10–17" laptops', 'Passive cooling ventilation'],
    translations: {
      hu: {
        name: 'Alumínium Laptop Állvány',
        tagline: 'Emeld meg a képernyőt, javítsd a tartásodat',
        description: 'Hat állítható magassági pozíció és masszív alumínium konstrukció – ez az utolsó állvány, amire az asztalodnak valaha szüksége lesz. A csúszásmentes szilikon talpak védik a laptopot és rögzítik az állványt a leghevesebb gépelési szessziókon is.',
        features: ['6 szögű magasságállítás', 'Tömör alumínium ötvözet', 'Csúszásmentes szilikon betétek', 'Összecsukható és hordozható', 'Kompatibilis 10–17"-os laptopokkal', 'Passzív hűtési szellőzés'],
      },
      tr: {
        name: 'Alüminyum Laptop Standı',
        tagline: 'Ekranınızı yükseltin, duruşunuzu iyileştirin',
        description: 'Altı ayarlanabilir yükseklik pozisyonu ve sağlam alüminyum yapı, masanızın hiç ihtiyaç duyacağı son standdır. Kaymaz silikon pedler laptopunuzu korur ve en yoğun yazma seanslarında standı yerinde tutar.',
        features: ['6 açılı yükseklik ayarı', 'Sağlam alüminyum alaşım', 'Kaymaz silikon pedler', 'Katlanabilir ve taşınabilir', '10–17" laptoplarla uyumlu', 'Pasif soğutma havalandırması'],
      },
    },
  },
  {
    id: 5,
    slug: 'wireless-charging-pad',
    name: 'Wireless Charging Pad',
    price: 49,
    originalPrice: null,
    category: 'Charging',
    tagline: 'Drop it and forget it',
    description: 'Up to 15W fast wireless charging with smart coil detection that works through cases up to 5mm thick. An LED breathing indicator tells you at a glance whether your device is charging—without blinding you at night.',
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1586816879360-004f5b0c51e3?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1605464315542-bda3e2f4e605?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.5,
    reviewCount: 193,
    inStock: true,
    lowStock: false,
    isBestseller: false,
    isNew: false,
    features: ['15W max output', 'Works through 5mm cases', 'Qi2 standard compatible', 'LED breathing indicator', 'Over-voltage protection', 'Anti-slip silicone base'],
    translations: {
      hu: {
        name: 'Vezeték nélküli Töltőpad',
        tagline: 'Tedd le és felejtsd el',
        description: 'Akár 15W-os gyors vezeték nélküli töltés intelligens tekercsérzékeléssel, amely 5mm vastag tokozaton keresztül is működik. Az LED légzési jelzőfény egyetlen pillantással megmutatja, töltödik-e az eszköz – anélkül, hogy éjjel vakítana.',
        features: ['Max. 15W teljesítmény', '5mm tokozaton áthat', 'Qi2 szabványos kompatibilis', 'LED légzési jelzőfény', 'Túlfeszültség-védelem', 'Csúszásmentes szilikon alap'],
      },
      tr: {
        name: 'Kablosuz Şarj Pedi',
        tagline: 'Bırak ve unut',
        description: '5mm kalınlığa kadar kılıflardan geçen akıllı bobin algılamasıyla 15W kadar hızlı kablosuz şarj. LED nefes göstergesi, cihazınızın şarj olup olmadığını tek bakışta söyler—gece sizi kör etmeden.',
        features: ['Maks. 15W çıkış', '5mm kılıflardan çalışır', 'Qi2 standart uyumlu', 'LED nefes göstergesi', 'Aşırı gerilim koruması', 'Kaymaz silikon taban'],
      },
    },
  },
  {
    id: 6,
    slug: '4k-pro-webcam',
    name: '4K Pro Webcam',
    price: 129,
    originalPrice: null,
    category: 'Workspace',
    tagline: 'Look sharper on every call',
    description: 'An 8MP Sony sensor with autofocus and a 90° field of view puts you in crystal-clear 4K on every video call. Built-in dual stereo mics with noise suppression mean your voice comes through even in a busy open office.',
    image: 'https://images.unsplash.com/photo-1500726726099-3f759a2eaa99?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1500726726099-3f759a2eaa99?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1622750342107-4b60e2704157?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.6,
    reviewCount: 156,
    inStock: true,
    lowStock: true,
    isBestseller: false,
    isNew: false,
    features: ['4K 30fps / 1080p 60fps', '8MP Sony sensor', 'Dual stereo mics + noise gate', '90° field of view', 'Auto light correction', 'Universal clip + tripod mount'],
    translations: {
      hu: {
        name: '4K Prémium Webkamera',
        tagline: 'Nézz élesebben minden hívásban',
        description: 'Egy 8MP-es Sony szenzor autófókusszal és 90°-os látószöggel kristálytiszta 4K képet nyújt minden videóhívásban. A beépített kétcsatornás sztereó mikrofonok zajszűréssel gondoskodnak arról, hogy a hangod akkor is átjön, ha zajos irodában dolgozol.',
        features: ['4K 30fps / 1080p 60fps', '8MP Sony szenzor', 'Kettős sztereó mikrofon + zajkapu', '90°-os látószög', 'Automatikus fénykorrekció', 'Univerzális csipesz + állványadapter'],
      },
      tr: {
        name: '4K Pro Web Kamerası',
        tagline: 'Her görüşmede daha keskin görünün',
        description: '8MP Sony sensör, otofokus ve 90° görüş açısıyla her video görüşmesinde kristal netliğinde 4K görüntü sunar. Yerleşik çift stereo mikrofon ve gürültü bastırma, sesinizin yoğun açık ofiste bile net duyulmasını sağlar.',
        features: ['4K 30fps / 1080p 60fps', '8MP Sony sensör', 'Çift stereo mikrofon + gürültü kapısı', '90° görüş açısı', 'Otomatik ışık düzeltme', 'Evrensel klips + tripod montajı'],
      },
    },
  },
  {
    id: 7,
    slug: 'xl-desk-pad',
    name: 'XL Desk Pad',
    price: 45,
    originalPrice: null,
    category: 'Workspace',
    tagline: 'Your whole desk, unified',
    description: 'A 90×40cm extended mouse pad with micro-textured surface optimised for both optical and laser sensors at any DPI. Stitched edges prevent fraying and the non-slip rubber base stays put through marathon sessions.',
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1593642634402-b0eb5e2eebc9?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1616628188506-bb241e26726b?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.7,
    reviewCount: 339,
    inStock: true,
    lowStock: false,
    isBestseller: false,
    isNew: false,
    features: ['90×40cm extended coverage', 'Micro-texture surface', 'Stitched anti-fray edges', 'Non-slip rubber backing', 'Waterproof coating', 'Works with all sensor types'],
    translations: {
      hu: {
        name: 'XL Asztali Egérpad',
        tagline: 'Az egész asztalod, egységesen',
        description: 'Egy 90×40 cm-es kiterjesztett egérpad mikrotexturált felülettel, optimalizálva optikai és lézeres érzékelőkhöz bármilyen DPI értéknél. A varrott szélek megakadályozzák a szálasodást, a csúszásmentes gumitalpak pedig maratoni szessziókon is a helyükön tartják.',
        features: ['90×40 cm-es kiterjedés', 'Mikrotexturált felület', 'Varrott, kopásálló szélek', 'Csúszásmentes gumitalpak', 'Vízálló bevonat', 'Minden érzékelőtípushoz kompatibilis'],
      },
      tr: {
        name: 'XL Masa Pedi',
        tagline: 'Tüm masanız, tek parça',
        description: 'Her DPI değerinde optik ve lazer sensörler için optimize edilmiş mikro dokulu yüzeyli 90×40cm genişletilmiş mouse pad. Dikişli kenarlar yıpranmayı önler ve kaymaz kauçuk taban maraton seanslarında yerinde kalır.',
        features: ['90×40cm geniş kapsama', 'Mikro dokulu yüzey', 'Dikişli yıpranmaz kenarlar', 'Kaymaz kauçuk arka yüzey', 'Su geçirmez kaplama', 'Tüm sensör türleriyle uyumlu'],
      },
    },
  },
  {
    id: 8,
    slug: 'monitor-light-bar',
    name: 'Monitor Light Bar',
    price: 79,
    originalPrice: null,
    category: 'Workspace',
    tagline: 'Light your work, not your screen',
    description: 'An asymmetric optical design casts even illumination across your desk while producing zero screen glare. Touch-sensitive dimming and a 2700–6500K colour temperature range let you dial in the perfect lighting for any task or time of day.',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.8,
    reviewCount: 211,
    inStock: true,
    lowStock: false,
    isBestseller: false,
    isNew: true,
    features: ['Zero screen glare optics', '2700–6500K colour range', 'Touch-sensitive control', 'USB-C powered', 'Clip-on, no-tool install', 'Memory last-used setting'],
    translations: {
      hu: {
        name: 'Monitor Fénysáv',
        tagline: 'Világítsd meg a munkát, ne a képernyőt',
        description: 'Az aszimmetrikus optikai kialakítás egyenletes megvilágítást terjeszt az asztalon, teljesen tükröződés nélkül. Az érintéses fényerőszabályozás és a 2700–6500K színhőmérséklet-tartomány lehetővé teszi, hogy minden feladathoz és napszakhoz beállítsd a tökéletes megvilágítást.',
        features: ['Tükröződésmentes optika', '2700–6500K színtartomány', 'Érintéses vezérlés', 'USB-C tápellátás', 'Csiptethető, szerszám nélküli felszerelés', 'Utolsó beállítás tárolása'],
      },
      tr: {
        name: 'Monitör Işık Çubuğu',
        tagline: 'Çalışmanızı aydınlatın, ekranı değil',
        description: 'Asimetrik optik tasarım, ekran parlamalarına neden olmadan masanıza eşit aydınlatma sağlar. Dokunmatik kısma kontrolü ve 2700–6500K renk sıcaklığı aralığı, her görev veya günün saati için mükemmel aydınlatmayı ayarlamanızı sağlar.',
        features: ['Sıfır ekran parlaması optikleri', '2700–6500K renk aralığı', 'Dokunmatik hassas kontrol', 'USB-C ile güçlendirilir', 'Klipsle monte, alet gerektirmez', 'Son kullanılan ayarı hatırlar'],
      },
    },
  },
  {
    id: 9,
    slug: 'noise-cancelling-earbuds',
    name: 'Noise-Cancelling Earbuds',
    price: 119,
    originalPrice: 149,
    category: 'Audio',
    tagline: 'Silence the world, hear your best',
    description: 'Four microphones work in tandem to model and cancel ambient noise in real time, while 10mm dynamic drivers deliver warmth and detail that punches far above the price. Six-hour battery plus the case adds 24 more—all day and then some.',
    image: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.7,
    reviewCount: 278,
    inStock: true,
    lowStock: false,
    isBestseller: true,
    isNew: false,
    features: ['4-mic hybrid ANC', '30-hour total battery', 'IPX4 water resistance', 'Transparency mode', 'Wireless charging case', 'Custom EQ via app'],
    translations: {
      hu: {
        name: 'Zajszűrő Fülhallgató',
        tagline: 'Csendesítsd el a világot, halld a legjobbat',
        description: 'Négy mikrofon valós időben modellezi és szűri ki a környezeti zajt, miközben 10mm-es dinamikus hangszórók olyan melegséget és részletgazdagságot nyújtanak, ami messze meghaladja az árkategóriát. Hat órás akkumulátor, a töltőtok további 24 órát ad – egész napra és még tovább.',
        features: ['4 mikrofonos hibrid ANC', '30 óra összesített akkumulátor', 'IPX4 vízállóság', 'Átlátszósági mód', 'Vezeték nélküli töltőtok', 'Egyedi EQ alkalmazáson keresztül'],
      },
      tr: {
        name: 'Gürültü Önleyici Kulak İçi Kulaklık',
        tagline: 'Dünyayı susturun, en iyi sesi duyun',
        description: 'Dört mikrofon gerçek zamanlı olarak ortam gürültüsünü modelleyip iptal ederken, 10mm dinamik sürücüler fiyatının çok üzerinde sıcaklık ve detay sunar. Altı saatlik pil artı kılıf 24 saat daha ekler—tüm gün ve biraz daha fazlası.',
        features: ['4 mikrofonlu hibrit ANC', '30 saat toplam pil', 'IPX4 suya dayanıklılık', 'Şeffaflık modu', 'Kablosuz şarjlı kılıf', 'Uygulama üzerinden özel EQ'],
      },
    },
  },
  {
    id: 10,
    slug: 'portable-ssd-1tb',
    name: 'Portable SSD 1TB',
    price: 109,
    originalPrice: null,
    category: 'Storage',
    tagline: '1 TB in your pocket, 1000 MB/s on tap',
    description: 'NVMe speeds in a pocket-sized aluminium shell. Transfer a 4K RAW file in seconds, not minutes. Drop-proof up to 1.5m and dust-tight, it is the professional backup drive that keeps up wherever you work.',
    image: 'https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1484662020986-75935d2ebc66?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.8,
    reviewCount: 164,
    inStock: true,
    lowStock: false,
    isBestseller: false,
    isNew: false,
    features: ['1000 MB/s read speed', 'USB 3.2 Gen 2 interface', '1.5m drop-proof tested', 'Aluminium alloy shell', 'USB-C & USB-A cables included', 'Compatible with PC, Mac, PS5'],
    translations: {
      hu: {
        name: 'Hordozható SSD 1TB',
        tagline: '1 TB a zsebedben, 1000 MB/s készen áll',
        description: 'NVMe sebesség zsebméretes alumínium házban. Másodpercek alatt vidd át a 4K RAW fájlt, ne percekig várj. 1,5 m-es esésállóság és portálló kialakítás – ez az a professzionális biztonsági mentési meghajtó, amely bárhol lépést tart veled.',
        features: ['1000 MB/s olvasási sebesség', 'USB 3.2 Gen 2 interfész', '1,5 m-es esésállóság tesztelve', 'Alumínium ötvözet ház', 'USB-C és USB-A kábel mellékelve', 'Kompatibilis PC-vel, Mac-kel, PS5-tel'],
      },
      tr: {
        name: 'Taşınabilir SSD 1TB',
        tagline: 'Cebinizde 1 TB, hazırda 1000 MB/s',
        description: 'Cep boyutlu alüminyum kılıfta NVMe hızları. 4K RAW dosyasını dakikalar değil saniyeler içinde aktarın. 1,5m düşme dayanımı ve toz koruması ile nerede çalışırsanız çalışın ayak uyduran profesyonel yedekleme sürücüsü.',
        features: ['1000 MB/s okuma hızı', 'USB 3.2 Gen 2 arayüzü', '1,5m düşme dayanımı test edildi', 'Alüminyum alaşım kılıf', 'USB-C ve USB-A kablo dahil', 'PC, Mac, PS5 ile uyumlu'],
      },
    },
  },
  {
    id: 11,
    slug: 'smart-desk-lamp',
    name: 'Smart Desk Lamp',
    price: 65,
    originalPrice: null,
    category: 'Workspace',
    tagline: 'Intelligent light for intelligent work',
    description: 'App-controlled brightness, a built-in USB-A charging port, and flicker-free LEDs rated at Ra>95 for true-to-life colour reproduction. A scene memory feature saves your last setting so your perfect work light is always one tap away.',
    image: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1519219788971-8d9797e0928e?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1621447980929-6638614633c8?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.5,
    reviewCount: 132,
    inStock: true,
    lowStock: false,
    isBestseller: false,
    isNew: false,
    features: ['Ra>95 colour rendering', 'App & touch control', 'Built-in USB-A port', 'Flicker-free LEDs', 'Scene memory', '360° flexible arm'],
    translations: {
      hu: {
        name: 'Okos Asztali Lámpa',
        tagline: 'Intelligens fény az intelligens munkához',
        description: 'Alkalmazásvezérelt fényerő, beépített USB-A töltőport és Ra>95 minősítésű vibrálásmentesLED-ek valósághű színvisszaadáshoz. A jelenetmemória funkció elmenti az utolsó beállítást, így a tökéletes munkafényed mindig egyetlen érintésre van.',
        features: ['Ra>95 színvisszaadás', 'Alkalmazás- és érintésvezérlés', 'Beépített USB-A port', 'Vibrálásmentesek LED-ek', 'Jelenetmemória', '360°-os rugalmas kar'],
      },
      tr: {
        name: 'Akıllı Masa Lambası',
        tagline: 'Akıllı çalışma için akıllı ışık',
        description: 'Uygulama kontrollü parlaklık, yerleşik USB-A şarj portu ve gerçek renkli görüntü için Ra>95 sertifikalı titreşimsiz LEDler. Sahne hafızası özelliği son ayarınızı kaydeder, böylece mükemmel çalışma ışığınız her zaman tek dokunuşla hazır.',
        features: ['Ra>95 renk görüntüleme', 'Uygulama ve dokunmatik kontrol', 'Yerleşik USB-A port', 'Titreşimsiz LEDler', 'Sahne hafızası', '360° esnek kol'],
      },
    },
  },
  {
    id: 12,
    slug: '65w-gan-charger',
    name: '65W GaN Charger',
    price: 59,
    originalPrice: null,
    category: 'Charging',
    tagline: 'Full-laptop power in a plug the size of a hockey puck',
    description: 'Gallium nitride technology packs 65W of output into a body 40% smaller than a conventional brick. Three ports charge laptop, phone, and earbuds simultaneously without thermal throttling.',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1605619682413-f8f5ad01d7d7?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1609740550069-8c1c77f53b58?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.9,
    reviewCount: 297,
    inStock: true,
    lowStock: false,
    isBestseller: false,
    isNew: true,
    features: ['65W USB-C PD output', 'GaN technology', '3-port simultaneous charging', '40% smaller than standard', 'Universal voltage 100–240V', 'Fold-flat prongs'],
    translations: {
      hu: {
        name: '65W GaN Töltő',
        tagline: 'Teljes laptop teljesítmény hockeykorong méretű dugóban',
        description: 'A gallium-nitrid technológia 65W teljesítményt zsúfol egy 40%-kal kisebb testbe, mint egy hagyományos tégla. Három port egyszerre tölti a laptopot, a telefont és a fülhallgatót hőfojtás nélkül.',
        features: ['65W USB-C PD kimenet', 'GaN technológia', '3 port egyidejű töltése', '40%-kal kisebb a szokványosnál', 'Univerzális feszültség 100–240V', 'Összecsukható dugólapok'],
      },
      tr: {
        name: '65W GaN Şarj Cihazı',
        tagline: 'Hokey puck boyutunda tam laptop gücü',
        description: 'Galyum nitrür teknolojisi, 65W çıkışı standart bir fişin %40 daha küçük bir gövdesine sığdırır. Üç port, termal kısma olmadan laptop, telefon ve kulaklığı aynı anda şarj eder.',
        features: ['65W USB-C PD çıkışı', 'GaN teknolojisi', '3 porta eş zamanlı şarj', 'Standarttan %40 daha küçük', 'Evrensel voltaj 100–240V', 'Katlanabilir pimler'],
      },
    },
  },
]

export function getProductBySlug(slug) {
  return PRODUCTS.find(p => p.slug === slug) || null
}

export function getRelatedProducts(product, count = 3) {
  return PRODUCTS
    .filter(p => p.id !== product.id && p.category === product.category)
    .slice(0, count)
    .concat(
      PRODUCTS.filter(p => p.id !== product.id && p.category !== product.category)
    )
    .slice(0, count)
}

export function localizeProduct(product, locale) {
  const t = product.translations?.[locale]
  if (!t) return product
  return {
    ...product,
    name: t.name ?? product.name,
    tagline: t.tagline ?? product.tagline,
    description: t.description ?? product.description,
    features: t.features ?? product.features,
  }
}
