export const PRODUCTS = [
  {
    id: 1,
    slug: 'pro-wireless-headphones',
    name: 'Pro Wireless Headphones',
    price: 149,
    originalPrice: 199,
    category: 'Audio',
    tagline: 'Studio-grade sound, all-day comfort',
    description: 'Experience music the way it was meant to be heard. The Pro Wireless Headphones deliver 40mm drivers tuned for audiophile-grade clarity across every genre. Adaptive noise cancellation and a 40-hour battery keep you in the zone from morning standup to late-night deep work.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1487215078519-e21cc028cb29?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.8,
    reviewCount: 312,
    inStock: true,
    lowStock: false,
    isBestseller: true,
    isNew: false,
    features: ['40-hour battery life', 'Active noise cancellation', 'Foldable premium design', 'USB-C fast charging', 'Hi-Res Audio certified', 'Multipoint Bluetooth 5.3'],
  },
  {
    id: 2,
    slug: 'mechanical-keyboard-tkl',
    name: 'Mechanical Keyboard TKL',
    price: 199,
    originalPrice: null,
    category: 'Workspace',
    tagline: 'Tactile precision, tenkeyless form',
    description: 'Built for those who live in the terminal. The TKL uses custom linear switches rated for 100 million keystrokes and a hot-swap PCB so you can re-tune your feel anytime. PBT double-shot keycaps resist fade years into daily use.',
    image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.7,
    reviewCount: 188,
    inStock: true,
    lowStock: false,
    isBestseller: false,
    isNew: true,
    features: ['Hot-swap PCB', 'PBT double-shot keycaps', 'USB-C detachable cable', 'Per-key RGB backlight', 'CNC aluminium case', 'Custom linear switches'],
  },
  {
    id: 3,
    slug: 'usb-c-hub-12-in-1',
    name: 'USB-C Hub 12-in-1',
    price: 89,
    originalPrice: null,
    category: 'Workspace',
    tagline: 'Every port you need, one cable',
    description: 'Reclaim every port on your laptop without sacrificing desk clarity. Twelve connections—HDMI 4K, USB-A 3.2, Ethernet, SD cards, and 100W PD passthrough—pack into an aluminium body smaller than your palm.',
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1625895197185-efcec01cffe0?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1563206767-5b18f218e8de?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.6,
    reviewCount: 245,
    inStock: true,
    lowStock: false,
    isBestseller: false,
    isNew: false,
    features: ['4K HDMI output', '100W Power Delivery', 'USB-A 3.2 Gen 2 (×3)', 'SD & microSD slots', 'Gigabit Ethernet', 'Aluminium heatsink body'],
  },
  {
    id: 4,
    slug: 'aluminum-laptop-stand',
    name: 'Aluminum Laptop Stand',
    price: 69,
    originalPrice: null,
    category: 'Workspace',
    tagline: 'Elevate your screen, elevate your posture',
    description: 'Six adjustable height positions and a solid aluminium build make this the last stand your desk will ever need. Non-slip silicone pads protect your laptop and keep the stand planted under the most intense typing sessions.',
    image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1593642634315-48f5414c3ad9?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.9,
    reviewCount: 427,
    inStock: true,
    lowStock: false,
    isBestseller: true,
    isNew: false,
    features: ['6-angle height adjustment', 'Solid aluminium alloy', 'Non-slip silicone pads', 'Foldable & portable', 'Compatible with 10–17" laptops', 'Passive cooling ventilation'],
  },
  {
    id: 5,
    slug: 'wireless-charging-pad',
    name: 'Wireless Charging Pad',
    price: 49,
    originalPrice: null,
    category: 'Charging',
    tagline: 'Drop it and forget it',
    description: 'Up to 15W fast wireless charging with smart coil detection that works through cases up to 5mm thick. An LED breathing indicator tells you at a glance whether your device is charging—without blinding you at night.',
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1586816879360-004f5b0c51e3?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1605464315542-bda3e2f4e605?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.5,
    reviewCount: 193,
    inStock: true,
    lowStock: false,
    isBestseller: false,
    isNew: false,
    features: ['15W max output', 'Works through 5mm cases', 'Qi2 standard compatible', 'LED breathing indicator', 'Over-voltage protection', 'Anti-slip silicone base'],
  },
  {
    id: 6,
    slug: '4k-pro-webcam',
    name: '4K Pro Webcam',
    price: 129,
    originalPrice: null,
    category: 'Workspace',
    tagline: 'Look sharper on every call',
    description: 'An 8MP Sony sensor with autofocus and a 90° field of view puts you in crystal-clear 4K on every video call. Built-in dual stereo mics with noise suppression mean your voice comes through even in a busy open office.',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.6,
    reviewCount: 156,
    inStock: true,
    lowStock: true,
    isBestseller: false,
    isNew: false,
    features: ['4K 30fps / 1080p 60fps', '8MP Sony sensor', 'Dual stereo mics + noise gate', '90° field of view', 'Auto light correction', 'Universal clip + tripod mount'],
  },
  {
    id: 7,
    slug: 'xl-desk-pad',
    name: 'XL Desk Pad',
    price: 45,
    originalPrice: null,
    category: 'Workspace',
    tagline: 'Your whole desk, unified',
    description: 'A 90×40cm extended mouse pad with micro-textured surface optimised for both optical and laser sensors at any DPI. Stitched edges prevent fraying and the non-slip rubber base stays put through marathon sessions.',
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1593642634402-b0eb5e2eebc9?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1616628188506-bb241e26726b?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.7,
    reviewCount: 339,
    inStock: true,
    lowStock: false,
    isBestseller: false,
    isNew: false,
    features: ['90×40cm extended coverage', 'Micro-texture surface', 'Stitched anti-fray edges', 'Non-slip rubber backing', 'Waterproof coating', 'Works with all sensor types'],
  },
  {
    id: 8,
    slug: 'monitor-light-bar',
    name: 'Monitor Light Bar',
    price: 79,
    originalPrice: null,
    category: 'Workspace',
    tagline: 'Light your work, not your screen',
    description: 'An asymmetric optical design casts even illumination across your desk while producing zero screen glare. Touch-sensitive dimming and a 2700–6500K colour temperature range let you dial in the perfect lighting for any task or time of day.',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.8,
    reviewCount: 211,
    inStock: true,
    lowStock: false,
    isBestseller: false,
    isNew: true,
    features: ['Zero screen glare optics', '2700–6500K colour range', 'Touch-sensitive control', 'USB-C powered', 'Clip-on, no-tool install', 'Memory last-used setting'],
  },
  {
    id: 9,
    slug: 'noise-cancelling-earbuds',
    name: 'Noise-Cancelling Earbuds',
    price: 119,
    originalPrice: 149,
    category: 'Audio',
    tagline: 'Silence the world, hear your best',
    description: 'Four microphones work in tandem to model and cancel ambient noise in real time, while 10mm dynamic drivers deliver warmth and detail that punches far above the price. Six-hour battery plus the case adds 24 more—all day and then some.',
    image: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.7,
    reviewCount: 278,
    inStock: true,
    lowStock: false,
    isBestseller: true,
    isNew: false,
    features: ['4-mic hybrid ANC', '30-hour total battery', 'IPX4 water resistance', 'Transparency mode', 'Wireless charging case', 'Custom EQ via app'],
  },
  {
    id: 10,
    slug: 'portable-ssd-1tb',
    name: 'Portable SSD 1TB',
    price: 109,
    originalPrice: null,
    category: 'Storage',
    tagline: '1 TB in your pocket, 1000 MB/s on tap',
    description: 'NVMe speeds in a pocket-sized aluminium shell. Transfer a 4K RAW file in seconds, not minutes. Drop-proof up to 1.5m and dust-tight, it is the professional backup drive that keeps up wherever you work.',
    image: 'https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1484662020986-75935d2ebc66?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.8,
    reviewCount: 164,
    inStock: true,
    lowStock: false,
    isBestseller: false,
    isNew: false,
    features: ['1000 MB/s read speed', 'USB 3.2 Gen 2 interface', '1.5m drop-proof tested', 'Aluminium alloy shell', 'USB-C & USB-A cables included', 'Compatible with PC, Mac, PS5'],
  },
  {
    id: 11,
    slug: 'smart-desk-lamp',
    name: 'Smart Desk Lamp',
    price: 65,
    originalPrice: null,
    category: 'Workspace',
    tagline: 'Intelligent light for intelligent work',
    description: 'App-controlled brightness, a built-in USB-A charging port, and flicker-free LEDs rated at Ra>95 for true-to-life colour reproduction. A scene memory feature saves your last setting so your perfect work light is always one tap away.',
    image: 'https://images.unsplash.com/photo-1580239096219-7f0a5fd58c28?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1580239096219-7f0a5fd58c28?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1513506003901-1e6a35e5eece?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.5,
    reviewCount: 132,
    inStock: true,
    lowStock: false,
    isBestseller: false,
    isNew: false,
    features: ['Ra>95 colour rendering', 'App & touch control', 'Built-in USB-A port', 'Flicker-free LEDs', 'Scene memory', '360° flexible arm'],
  },
  {
    id: 12,
    slug: '65w-gan-charger',
    name: '65W GaN Charger',
    price: 59,
    originalPrice: null,
    category: 'Charging',
    tagline: 'Full-laptop power in a plug the size of a hockey puck',
    description: 'Gallium nitride technology packs 65W of output into a body 40% smaller than a conventional brick. Three ports charge laptop, phone, and earbuds simultaneously without thermal throttling.',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=900&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1605619682413-f8f5ad01d7d7?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1609740550069-8c1c77f53b58?w=900&q=80&auto=format&fit=crop',
    ],
    rating: 4.9,
    reviewCount: 297,
    inStock: true,
    lowStock: false,
    isBestseller: false,
    isNew: true,
    features: ['65W USB-C PD output', 'GaN technology', '3-port simultaneous charging', '40% smaller than standard', 'Universal voltage 100–240V', 'Fold-flat prongs'],
  },
]

export function getProductBySlug(slug) {
  return PRODUCTS.find(p => p.slug === slug) || null
}

export function getRelatedProducts(product, count = 3) {
  return PRODUCTS
    .filter(p => p.id !== product.id && p.category === product.category)
    .slice(0, count)
    .concat(
      PRODUCTS.filter(p => p.id !== product.id && p.category !== product.category)
    )
    .slice(0, count)
}
